-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MemberAccess/sql/memberaccess_entry.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/memberaccess_entry (
  mae_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  mae_group_id INTEGER UNSIGNED NOT NULL,
  mae_value BLOB NOT NULL, mae_kind BLOB NOT NULL,
  mae_actor BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  mae_timestamp BLOB NOT NULL, mae_invited BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX mae_value ON /*_*/memberaccess_entry (mae_value);

CREATE INDEX mae_group_id_value ON /*_*/memberaccess_entry (mae_group_id, mae_value);
