-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MemberAccess/sql/memberaccess_group.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/memberaccess_group (
  mag_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  mag_name BLOB NOT NULL, mag_timestamp BLOB NOT NULL
);
