-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MemberAccess/sql/memberaccess_member.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/memberaccess_member (
  mam_user_id INTEGER UNSIGNED NOT NULL,
  mam_email BLOB NOT NULL,
  mam_group_id INTEGER UNSIGNED NOT NULL,
  mam_timestamp BLOB NOT NULL,
  mam_deactivated BLOB DEFAULT NULL,
  mam_last_login BLOB DEFAULT NULL,
  PRIMARY KEY(mam_user_id)
);

CREATE INDEX mam_group_id ON /*_*/memberaccess_member (mam_group_id);

CREATE INDEX mam_email ON /*_*/memberaccess_member (mam_email);
