-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/MemberAccess/sql/abstractSchemaChanges/patch-memberaccess_entry-mae_invited.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/memberaccess_entry
  ADD COLUMN mae_invited BLOB DEFAULT NULL;
