name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'REL1_43'
            php: '8.3'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v5
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}_v2

      - name: Cache Composer cache
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - uses: actions/checkout@v6
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installMediaWiki.sh ${{ matrix.mw }} MemberAccess

      - uses: actions/checkout@v6
        with:
          path: mediawiki/extensions/MemberAccess

      - run: composer update

      - name: Run update.php
        run: php maintenance/run.php update --quick

      - name: Run PHPUnit with code coverage
        run: php tests/phpunit/phpunit.php -c extensions/MemberAccess/ --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_GLOBAL_TOKEN }}
          slug: ProfessionalWiki/MemberAccess

  PHPStan:
    name: "PHPStan: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'REL1_43'
            php: '8.3'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          tools: composer, cs2pr

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v5
        with:
          path: |
            mediawiki
            mediawiki/extensions/
            mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}_v2

      - name: Cache Composer cache
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache
          key: composer_static_analysis

      - uses: actions/checkout@v6
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installMediaWiki.sh ${{ matrix.mw }} MemberAccess

      - uses: actions/checkout@v6
        with:
          path: mediawiki/extensions/MemberAccess

      - name: Composer allow-plugins
        run: composer config --no-plugins allow-plugins.composer/installers true

      - run: composer update

      - name: Composer install
        run: cd extensions/MemberAccess && composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: PHPStan
        run: cd extensions/MemberAccess && php vendor/bin/phpstan analyse --error-format=checkstyle --no-progress | cs2pr

  phpcs:
    name: "Code style: PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - php: '8.3'

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - uses: actions/checkout@v6

      - name: Cache Composer cache
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - name: Composer install
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - run: vendor/bin/phpcs -p -s
