-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MemberAccess/sql/memberaccess_group.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/memberaccess_group (
  mag_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  mag_name VARBINARY(255) NOT NULL,
  mag_timestamp BINARY(14) NOT NULL,
  PRIMARY KEY(mag_id)
) /*$wgDBTableOptions*/;
