-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MemberAccess/sql/memberaccess_member.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/memberaccess_member (
  mam_user_id INT UNSIGNED NOT NULL,
  mam_email VARBINARY(255) NOT NULL,
  mam_group_id INT UNSIGNED NOT NULL,
  mam_timestamp BINARY(14) NOT NULL,
  mam_deactivated BINARY(14) DEFAULT NULL,
  mam_last_login BINARY(14) DEFAULT NULL,
  INDEX mam_group_id (mam_group_id),
  INDEX mam_email (mam_email),
  PRIMARY KEY(mam_user_id)
) /*$wgDBTableOptions*/;
