-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MemberAccess/sql/memberaccess_entry.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/memberaccess_entry (
  mae_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  mae_group_id INT UNSIGNED NOT NULL,
  mae_value VARBINARY(255) NOT NULL,
  mae_kind VARBINARY(8) NOT NULL,
  mae_actor BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  mae_timestamp BINARY(14) NOT NULL,
  mae_invited BINARY(14) DEFAULT NULL,
  UNIQUE INDEX mae_value (mae_value),
  INDEX mae_group_id_value (mae_group_id, mae_value),
  PRIMARY KEY(mae_id)
) /*$wgDBTableOptions*/;
